language: node_js
node_js:
 - "node"

services:
 - docker

stages:
 -unit test
 -integration test
 -zap owasp test
 -deploy

jobs:
 include:
  - stage: unit test
    script: npm run unittest
  - stage: integration test
    script: npm run ittest
  - stage: zap owasp test
    script:
      - docker build -t ecreyes/ms-noticias-api .
      - docker run -d --name msnoticiasapi -e "process.env.MODE=test" -t ecreyes/ms-noticias-api
      - sleep 15
    after_script:
       - docker run --name owasp --link msnoticiasapi -t owasp/zap2docker-weekly zap-full-scan.py -t http://msnoticiasapi:3000
  - stage: deploy
    script:
      - docker build -t ecreyes/ms-noticias-api .
      - docker push ecreyes/ms-noticias-api

before_install:
#Docker login
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

branches:
 only:
  -master
  -owasp